# Code Used for Making the Following Datasets to Be Used
code by Maddie Warndorf
1. Collection Site Data
    - tp02waterdata.csv
    - tp04waterdata.csv
    - tp05waterdata.csv
2. Tempe Census Data
    - TempeCensus.csv
3. EMS Opioid Related Call Data
    - emsCountPerTractAllTempe.pkl NOT AGGREGATED BY MONTH IT IS TOTAL # CALLS BY TRACT
    - emsPulledData.csv This is the csv version of the JSON pull from the EMS Feature Layer
    - emsPulledData.pkl This is the pickled JSON pull from the EMS Feature Layer
    
    - emsCensusTract0118_0819.pkl This is total # Calls by Tract Aggregated by Month/Year
    - emsCensusTract_Month.pkl This is total # Calls by Tract Aggregated by Month
    
    - emsCallsTP02Census_mnyr.pkl This is total # Calls by Tract Aggregated by Month/Year in Area 2
    - emsCallsTP04Census_mnyr.pkl This is total # Calls by Tract Aggregated by Month/Year in Area 4
    - emsCallsTP05Census_mnyr.pkl This is total # Calls by Tract Aggregated by Month/Year in Area 5
    - emsWastewaterSites_mnyr.pkl This is total # Calls by Tract Aggregated by Month/Year for all collection sites
    
    - emsCallsTP02Census.pkl This is total # Calls by Tract Aggregated by Month in Area 2
    - emsCallsTP04Census.pkl This is total # Calls by Tract Aggregated by Month in Area 4
    - emsCallsTP05Census.pkl This is total # Calls by Tract Aggregated by Month in Area 5
    - emsWastewaterSites.pkl This is total # Calls by Tract Aggregated by Month for all collection sites
    - emsCallsNotCollectionSiteCensus_mnyr.pkl This is total # Calls by Tract Aggregated by Month/Year for all non-collection sites
    - emsCallsNotCollectionSiteCensus.pkl This is total # Calls by Tract Aggregated by Month for all non-collection sites

## Collection Site Datasets
https://www.arcgis.com/home/item.html?id=93ee24cbf945405c8469742555670fc5#data The data that is collected and stored via this code is pulled from the query requests for the data within the charts on the dashboard.

Feature Layer of Collection Sites
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=

In [8]:
#packages needed
import requests
import pandas as pd
import feedparser
from bs4 import BeautifulSoup
import urllib.request
import urllib3
import json
from pandas.io.json import json_normalize
from datetime import datetime
import math 
import geopandas as gpd

### Area TP02
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP02%27

In [2]:
url = 'https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP02%27'
resp = requests.get(url)
print(resp)

data_raw = resp.json()
data_raw.keys()

<Response [200]>

dict_keys(['objectIdFieldName', 'uniqueIdField', 'globalIdFieldName', 'fields', 'features'])

In [3]:
data_raw['features']
tp02_data = pd.io.json.json_normalize(data_raw['features'])
tp02_data.columns = ["Chemical","Concentration_ng_L_Error","Concentration_ng_L_Value","Day","Mass_Load_g_d_Error","Mass_Load_g_d_Value","Month","OBJECTID","Population_Normalized_Mass_Lo_1","Population_Normalized_Mass_Load","Sample_Date","Site"]

In [6]:
times = []
for t in tp02_data["Sample_Date"]:
    t1 = str(t)
    t2 = t1[0:10]
    t2 = int(t2)
    time = datetime.fromtimestamp(t2)
    times.append(time)
tp02_data["Sample_Date"] = times
tp02_data.head()

,Chemical,Concentration_ng_L_Error,Concentration_ng_L_Value,Day,Mass_Load_g_d_Error,Mass_Load_g_d_Value,Month,OBJECTID,Population_Normalized_Mass_Lo_1,Population_Normalized_Mass_Load,Sample_Date,Site
0,Oxycodone,4.26,101.37,(1) Mon,0.06,1.51,(05) May,1,0,24.77,2018-05-14 03:00:00,TP02
1,Oxycodone,2.33,106.94,(2) Tue,0.04,1.68,(05) May,2,0,27.54,2018-05-15 03:00:00,TP02
2,Oxycodone,1.81,102.03,(3) Wed,0.03,1.60,(05) May,3,0,26.22,2018-05-16 03:00:00,TP02
3,Oxycodone,5.34,115.53,(4) Thu,0.08,1.78,(05) May,4,0,29.27,2018-05-17 03:00:00,TP02
4,Oxycodone,4.22,103.88,(5) Fri,0.06,1.54,(05) May,5,0,25.28,2018-05-18 03:00:00,TP02

In [11]:
tp02_data.drop(['OBJECTID'], axis=1, inplace=True)

In [12]:
tp02_data.head()

,Chemical,Concentration_ng_L_Error,Concentration_ng_L_Value,Day,Mass_Load_g_d_Error,Mass_Load_g_d_Value,Month,Population_Normalized_Mass_Lo_1,Population_Normalized_Mass_Load,Sample_Date,Site
0,Oxycodone,4.26,101.37,(1) Mon,0.06,1.51,(05) May,0,24.77,2018-05-14 03:00:00,TP02
1,Oxycodone,2.33,106.94,(2) Tue,0.04,1.68,(05) May,0,27.54,2018-05-15 03:00:00,TP02
2,Oxycodone,1.81,102.03,(3) Wed,0.03,1.60,(05) May,0,26.22,2018-05-16 03:00:00,TP02
3,Oxycodone,5.34,115.53,(4) Thu,0.08,1.78,(05) May,0,29.27,2018-05-17 03:00:00,TP02
4,Oxycodone,4.22,103.88,(5) Fri,0.06,1.54,(05) May,0,25.28,2018-05-18 03:00:00,TP02

In [13]:
tp02_data.to_csv(r'DataFiles/tp02waterdata.csv')

### Area TP04
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP04%27

In [14]:
url = 'https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP04%27'
resp = requests.get(url)
print(resp)

data_raw = resp.json()
data_raw.keys()

<Response [200]>

dict_keys(['objectIdFieldName', 'uniqueIdField', 'globalIdFieldName', 'fields', 'features'])

In [15]:
data_raw['features']
tp04_data = pd.io.json.json_normalize(data_raw['features'])
tp04_data.columns = ["Chemical","Concentration_ng_L_Error","Concentration_ng_L_Value","Day","Mass_Load_g_d_Error","Mass_Load_g_d_Value","Month","OBJECTID","Population_Normalized_Mass_Lo_1","Population_Normalized_Mass_Load","Sample_Date","Site"]

In [16]:
times = []
for t in tp04_data["Sample_Date"]:
    t1 = str(t)
    t2 = t1[0:10]
    t2 = int(t2)
    time = datetime.fromtimestamp(t2)
    times.append(time)
tp04_data["Sample_Date"] = times
tp04_data.drop(['OBJECTID'], axis=1, inplace=True)
tp04_data.head()

,Chemical,Concentration_ng_L_Error,Concentration_ng_L_Value,Day,Mass_Load_g_d_Error,Mass_Load_g_d_Value,Month,Population_Normalized_Mass_Lo_1,Population_Normalized_Mass_Load,Sample_Date,Site
0,Oxycodone,1.11,40.54,(1) Mon,0.01,0.26,(05) May,0,47.26,2018-05-14 03:00:00,TP04
1,Oxycodone,9999.99,9999.99,(2) Tue,9999.99,9999.99,(05) May,10000,9999.99,2018-05-15 03:00:00,TP04
2,Oxycodone,2.03,45.45,(3) Wed,0.01,0.32,(05) May,0,58.30,2018-05-16 03:00:00,TP04
3,Oxycodone,0.32,48.86,(4) Thu,0.00,0.33,(05) May,0,60.19,2018-05-17 03:00:00,TP04
4,Oxycodone,0.31,36.50,(5) Fri,0.00,0.22,(05) May,0,40.99,2018-05-18 03:00:00,TP04

In [17]:
tp04_data.to_csv(r'DataFiles/tp04waterdata.csv')

### Area TP05
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP05%27

In [18]:
url = 'https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/1/query?f=json&outFields=*&returnGeometry=false&where=Site%3D%27TP05%27'
resp = requests.get(url)
print(resp)

data_raw = resp.json()
data_raw.keys()
data_raw['features']
tp05_data = pd.io.json.json_normalize(data_raw['features'])
tp05_data.columns = ["Chemical","Concentration_ng_L_Error","Concentration_ng_L_Value","Day","Mass_Load_g_d_Error","Mass_Load_g_d_Value","Month","OBJECTID","Population_Normalized_Mass_Lo_1","Population_Normalized_Mass_Load","Sample_Date","Site"]

<Response [200]>

In [19]:
times = []
for t in tp05_data["Sample_Date"]:
    t1 = str(t)
    t2 = t1[0:10]
    t2 = int(t2)
    time = datetime.fromtimestamp(t2)
    times.append(time)
tp05_data["Sample_Date"] = times
tp05_data.drop(['OBJECTID'], axis=1, inplace=True)
tp05_data.head()

,Chemical,Concentration_ng_L_Error,Concentration_ng_L_Value,Day,Mass_Load_g_d_Error,Mass_Load_g_d_Value,Month,Population_Normalized_Mass_Lo_1,Population_Normalized_Mass_Load,Sample_Date,Site
0,Oxycodone,5.33,66.98,(1) Mon,0.00,0.05,(05) May,0,16.0,2018-05-14 03:00:00,TP05
1,Oxycodone,1.37,59.28,(2) Tue,0.00,0.04,(05) May,0,14.0,2018-05-15 03:00:00,TP05
2,Oxycodone,12.73,109.41,(3) Wed,0.01,0.07,(05) May,0,26.0,2018-05-16 03:00:00,TP05
3,Oxycodone,0.10,28.10,(4) Thu,0.00,0.02,(05) May,0,6.0,2018-05-17 03:00:00,TP05
4,Oxycodone,5.94,81.24,(5) Fri,0.00,0.05,(05) May,0,17.0,2018-05-18 03:00:00,TP05

In [20]:
tp05_data.to_csv(r'DataFiles/tp05waterdata.csv')

## Tempe Census Tracts Information

making of TempeCensus.csv

Tempe Census Feature Layer:
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Map/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=

In [21]:
#Packages Used
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import geopandas as gpd
from shapely.geometry import Point, Polygon
import pickle as pkl
from descartes import PolygonPatch

import requests
import pandas as pd
import feedparser
from bs4 import BeautifulSoup
import urllib.request
import urllib3
import json
from pandas.io.json import json_normalize

In [22]:
tempe = gpd.read_file("https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Map/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=")

Desired columns are as follows:
    TempeTracts_NAME: census tract number
    columns dealing with Age:
        - pdb2018trv4_us_csv_pct_Pop_un_
        - pdb2018trv4_us_csv_pct_Pop_5_18
        - pdb2018trv4_us_csv_pct_Pop_18_3
        - pdb2018trv4_us_csv_pct_Pop_25_5
        - pdb2018trv4_us_csv_pct_Pop_45_7
        - pdb2018trv4_us_csv_pct_Pop_65_1
    columns dealing with Employment:
        - pdb2018trv4_us_csv_pct_Civ_emp_
        - pdb2018trv4_us_csv_pct_Civ_em_1
        - pdb2018trv4_us_csv_pct_Civ_em_3
        - pdb2018trv4_us_csv_pct_Civ_em_5
    columns dealing with Unemployment:
        - pdb2018trv4_us_csv_pct_Civ_unem
        - pdb2018trv4_us_csv_pct_Civ_un_2
        - pdb2018trv4_us_csv_pct_Civ_un_4
        - pdb2018trv4_us_csv_pct_Civ_un_6
    columns dealing with Education:
        - pdb2018trv4_us_csv_pct_Not_HS_G
        - pdb2018trv4_us_csv_pct_College_
    columns dealing with Health Insurance:
        - pdb2018trv4_us_csv_pct_No_Healt
        - pdb2018trv4_us_csv_pct_One_Heal
        - pdb2018trv4_us_csv_pct_TwoPHeal
    column dealing with Below Poverty:
        - pdb2018trv4_us_csv_pct_Prs_Blw_

In [23]:
desired_tract_columns = ['TempeTracts_NAME',
                         'pdb2018trv4_us_csv_pct_Pop_un_1','pdb2018trv4_us_csv_pct_Pop_5_18','pdb2018trv4_us_csv_pct_Pop_18_3','pdb2018trv4_us_csv_pct_Pop_25_5',
              'pdb2018trv4_us_csv_pct_Pop_45_7','pdb2018trv4_us_csv_pct_Pop_65_1',
                         'pdb2018trv4_us_csv_pct_Civ_emp_',
                         'pdb2018trv4_us_csv_pct_Civ_em_1','pdb2018trv4_us_csv_pct_Civ_em_3','pdb2018trv4_us_csv_pct_Civ_em_5',
                         'pdb2018trv4_us_csv_pct_Civ_unem',
                         'pdb2018trv4_us_csv_pct_Civ_un_2','pdb2018trv4_us_csv_pct_Civ_un_4','pdb2018trv4_us_csv_pct_Civ_un_6',
                         'pdb2018trv4_us_csv_pct_Not_HS_G','pdb2018trv4_us_csv_pct_College_',
                         'pdb2018trv4_us_csv_pct_No_Healt','pdb2018trv4_us_csv_pct_One_Heal','pdb2018trv4_us_csv_pct_TwoPHeal',
                         'pdb2018trv4_us_csv_pct_Prs_Blw_',
                         'geometry']
tempe_tract_df = tempe[desired_tract_columns]

tempe_tract_df.columns = ['TempeTracts_NAME','PctPopUnder5','PctPop5_17','PctPop18_24','PctPop25_44','PctPop45_64','PctPop65_Up',
                        'PctEmpUnder16','PctEmp16_24','PctEmp25_44','PctEmp45_64',
                        'PctUnempUnder16','PctUnemp16_24','PctUnemp25_44','PctUnemp45_64',
                        'PctCollegeGrad','PctNotHSGrad',
                        'PctNoHealthIns','PctOneHealthIns','PctTwoHealthIns',
                        'PctBelowPoverty','geometry']

tempe_tract_df.to_csv(r'DataFiles/TempeCensusPulled.csv')

## EMS Opioid Related Calls in Tempe (Based on Census Tract)

EMS Call Feature Layer:
https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Opioid_Calls/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=

In [124]:
eurl = 'https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Opioid_Calls/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token='
ems = gpd.read_file(eurl)

surl = 'https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Wastewater_Study_Areas/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token='
sa = gpd.read_file(surl)
sa.drop(['OBJECTID'], axis=1, inplace=True)

tempe = gpd.read_file("https://services.arcgis.com/lQySeXwbBg53XWDi/arcgis/rest/services/Map/FeatureServer/0/query?where=OBJECTID+%3E+0+&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&returnCentroid=false&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=4326&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson&token=")

In [126]:
ems_all = pd.DataFrame()
for i in range(len(tempe)):
    df = ems[ems.within(tempe.loc[i,'geometry'])]
    ems_all = ems_all.append(df)
ems_all.head()
ems_all.drop(['OBJECTID'], axis=1, inplace=True)

In [127]:
#All EMS Calls that are Opioid related and from the dates 01/2018-08/2019
#MAY NEED TO EDIT DUE TO DATES
ems_allc = ems_all[ems_all['Opioid_Use'] == 'Yes']
ems_allc = ems_allc[ems_allc['Year'] != 2017]
ems_allc.head()

,Incident_Date,Weekday,Weekday_Sort,Month,Month_Sort,Year,Opioid_Use,Narcan_Given,Age,Patient_Gender,Patient_ASU,Patient_Veteran,Patient_Homeless,Latitude_Random,Longitude_Random,Spec_Pop,Notes,Time_of_Day,geometry
453,1516060800000,Tuesday,(3) Tuesday,January,(01) January,2018,Yes,Yes,20 to 24,Male,Unknown,Unknown,Unknown,33.4241,-111.9532,None,None,Evening,POINT (-111.95320 33.42410)
468,1517443200000,Thursday,(5) Thursday,February,(02) February,2018,Yes,NULL,25 to 29,Male,No,Yes,No,33.4230,-111.9436,Veteran,None,Overnight,POINT (-111.94360 33.42300)
479,1518739200000,Friday,(6) Friday,February,(02) February,2018,Yes,NULL,55 to 59,Female,No,Unknown,Unknown,33.4309,-111.9475,None,None,Evening,POINT (-111.94750 33.43090)
523,1521504000000,Tuesday,(3) Tuesday,March,(03) March,2018,Yes,NULL,25 to 29,Male,No,No,No,33.4288,-111.9567,None,None,Afternoon,POINT (-111.95670 33.42880)
571,1524700800000,Thursday,(5) Thursday,April,(04) April,2018,Yes,Yes,35 to 39,Male,No,No,No,33.4255,-111.9572,None,None,Morning,POINT (-111.95720 33.42550)

In [131]:
with open('DataFiles/emsPulledData.pkl', 'wb') as pkl_file:
    pkl.dump(ems_allc, pkl_file)
ems_allc.to_csv('DataFiles/emsPulledData.csv')

In [129]:
#Making EMS_Tract Dataframe - has Tract Name, Tract Geometry, Age columns, Num EMS Opioid Calls in Tract
desired_tract_columns = ['TempeTracts_NAME',
                         'pdb2018trv4_us_csv_pct_Pop_un_1','pdb2018trv4_us_csv_pct_Pop_5_18','pdb2018trv4_us_csv_pct_Pop_18_3','pdb2018trv4_us_csv_pct_Pop_25_5',
              'pdb2018trv4_us_csv_pct_Pop_45_7','pdb2018trv4_us_csv_pct_Pop_65_1',
                         'pdb2018trv4_us_csv_pct_Civ_emp_',
                         'pdb2018trv4_us_csv_pct_Civ_em_1','pdb2018trv4_us_csv_pct_Civ_em_3','pdb2018trv4_us_csv_pct_Civ_em_5',
                         'pdb2018trv4_us_csv_pct_Civ_unem',
                         'pdb2018trv4_us_csv_pct_Civ_un_2','pdb2018trv4_us_csv_pct_Civ_un_4','pdb2018trv4_us_csv_pct_Civ_un_6',
                         'pdb2018trv4_us_csv_pct_Not_HS_G','pdb2018trv4_us_csv_pct_College_',
                         'pdb2018trv4_us_csv_pct_No_Healt','pdb2018trv4_us_csv_pct_One_Heal','pdb2018trv4_us_csv_pct_TwoPHeal',
                         'pdb2018trv4_us_csv_pct_Prs_Blw_',
                         'geometry']
ems_tract_df = tempe[desired_tract_columns]
ems_tract_df.columns = ['TempeTracts_NAME','PctPopUnder5','PctPop5_17','PctPop18_24','PctPop25_44','PctPop45_64','PctPop65_Up',
                        'PctEmpUnder16','PctEmp16_24','PctEmp25_44','PctEmp45_64',
                        'PctUnempUnder16','PctUnemp16_24','PctUnemp25_44','PctUnemp45_64',
                        'PctCollegeGrad','PctNotHSGrad',
                        'PctNoHealthIns','PctOneHealthIns','PctTwoHealthIns',
                        'PctBelowPoverty','geometry']
num_calls = []

for i in range(len(tempe)):
    df = ems_allc[ems_allc.within(tempe.loc[i,'geometry'])]
    nc = len(df)
    num_calls.append(nc)

ems_tract_df["Num_EMS_Calls"] = num_calls
ems_tract_df.head()

/Users/maddiewarndorf/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,TempeTracts_NAME,PctPopUnder5,PctPop5_17,PctPop18_24,PctPop25_44,PctPop45_64,PctPop65_Up,PctEmpUnder16,PctEmp16_24,PctEmp25_44,...,PctUnemp25_44,PctUnemp45_64,PctCollegeGrad,PctNotHSGrad,PctNoHealthIns,PctOneHealthIns,PctTwoHealthIns,PctBelowPoverty,geometry,Num_EMS_Calls
0,3188,3.31,5.66,34.89,40.73,10.60,4.81,96.81,97.12,96.58,...,3.42,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.96132 33.43719, -111.96132 33.4...",14
1,3191.01,2.96,7.20,62.63,21.26,5.95,0.00,87.71,91.14,83.30,...,16.70,16.95,16.26,36.48,23.23,70.40,6.37,73.11,"POLYGON ((-111.92629 33.41915, -111.92611 33.4...",2
2,3189,3.38,6.06,31.45,31.21,19.71,8.20,93.78,95.67,92.52,...,7.48,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.96090 33.42195, -111.95857 33.4...",17
3,3190,0.82,2.07,81.56,10.22,3.72,1.60,88.55,85.07,100.00,...,0.00,0.00,0.00,63.30,10.87,77.17,11.96,34.24,"POLYGON ((-111.94358 33.41505, -111.94357 33.4...",12
4,3194.03,5.90,16.18,10.82,29.77,23.43,13.90,93.86,94.95,97.73,...,2.27,13.32,4.53,38.78,15.67,67.41,16.80,21.39,"POLYGON ((-111.90912 33.39411, -111.90912 33.3...",11

In [130]:
#Pickling ems_tract_df which contains the dataframe of all of Tempe with EMS Call data
#THIS IS NOT BROKEN DOWN BY MONTH!!!
with open('DataFiles/emsCountPerTractAllTempe.pkl', 'wb') as pkl_file:
    pkl.dump(ems_tract_df, pkl_file)

**This is to get the EMS Opioid call data aggregated by month-year for each tract.

In [132]:
infile = open('DataFiles/emsPulledData.pkl','rb')
ems_test = pkl.load(infile)
infile.close()

In [136]:
from time import strptime

ems_test['Weekday'] = ems_test['Weekday'].apply(lambda x: strptime(x,'%A').tm_wday)
ems_test['Month'] = ems_test['Month'].apply(lambda x: strptime(x,'%B').tm_mon)

ems_test["Date"] = ems_test["Month"].map(str) + '/' + ems_test['Weekday'].map(str) + '/' + ems_test["Year"].map(str)

ems_test.head()

,Incident_Date,Weekday,Weekday_Sort,Month,Month_Sort,Year,Opioid_Use,Narcan_Given,Age,Patient_Gender,...,Patient_Veteran,Patient_Homeless,Latitude_Random,Longitude_Random,Spec_Pop,Notes,Time_of_Day,geometry,Sample_Date,Date
453,1516060800000,1,(3) Tuesday,1,(01) January,2018,Yes,Yes,20 to 24,Male,...,Unknown,Unknown,33.4241,-111.9532,None,None,Evening,POINT (-111.95320 33.42410),2018-01-15 19:00:00,1/1/2018
468,1517443200000,3,(5) Thursday,2,(02) February,2018,Yes,NULL,25 to 29,Male,...,Yes,No,33.4230,-111.9436,Veteran,None,Overnight,POINT (-111.94360 33.42300),2018-01-31 19:00:00,2/3/2018
479,1518739200000,4,(6) Friday,2,(02) February,2018,Yes,NULL,55 to 59,Female,...,Unknown,Unknown,33.4309,-111.9475,None,None,Evening,POINT (-111.94750 33.43090),2018-02-15 19:00:00,2/4/2018
523,1521504000000,1,(3) Tuesday,3,(03) March,2018,Yes,NULL,25 to 29,Male,...,No,No,33.4288,-111.9567,None,None,Afternoon,POINT (-111.95670 33.42880),2018-03-19 20:00:00,3/1/2018
571,1524700800000,3,(5) Thursday,4,(04) April,2018,Yes,Yes,35 to 39,Male,...,No,No,33.4255,-111.9572,None,None,Morning,POINT (-111.95720 33.42550),2018-04-25 20:00:00,4/3/2018

In [137]:
times = []
for t in ems_test["Date"]:
    time = datetime.strptime(t, "%m/%w/%Y")
    times.append(time)
ems_test["Date"] = times
ems_test['Month_Year'] = pd.to_datetime(ems_test['Date']).dt.to_period('M')

In [138]:
ems_test.drop(['Date'], axis=1, inplace=True)
ems_test.head()

,Incident_Date,Weekday,Weekday_Sort,Month,Month_Sort,Year,Opioid_Use,Narcan_Given,Age,Patient_Gender,Patient_ASU,Patient_Veteran,Patient_Homeless,Latitude_Random,Longitude_Random,Spec_Pop,Notes,Time_of_Day,geometry,Month_Year
453,1516060800000,1,(3) Tuesday,1,(01) January,2018,Yes,Yes,20 to 24,Male,Unknown,Unknown,Unknown,33.4241,-111.9532,None,None,Evening,POINT (-111.95320 33.42410),2018-01
468,1517443200000,3,(5) Thursday,2,(02) February,2018,Yes,NULL,25 to 29,Male,No,Yes,No,33.4230,-111.9436,Veteran,None,Overnight,POINT (-111.94360 33.42300),2018-02
479,1518739200000,4,(6) Friday,2,(02) February,2018,Yes,NULL,55 to 59,Female,No,Unknown,Unknown,33.4309,-111.9475,None,None,Evening,POINT (-111.94750 33.43090),2018-02
523,1521504000000,1,(3) Tuesday,3,(03) March,2018,Yes,NULL,25 to 29,Male,No,No,No,33.4288,-111.9567,None,None,Afternoon,POINT (-111.95670 33.42880),2018-03
571,1524700800000,3,(5) Thursday,4,(04) April,2018,Yes,Yes,35 to 39,Male,No,No,No,33.4255,-111.9572,None,None,Morning,POINT (-111.95720 33.42550),2018-04

In [98]:
ems_test.drop(['Sample_Date'], axis=1, inplace=True)
ems_test.drop(['Date'], axis=1, inplace=True)
ems_test.head()

,OBJECTID,Incident_Date,Weekday,Weekday_Sort,Month,Month_Sort,Year,Opioid_Use,Narcan_Given,Age,...,Patient_ASU,Patient_Veteran,Patient_Homeless,Latitude_Random,Longitude_Random,Spec_Pop,Notes,Time_of_Day,geometry,Month_Year
453,454,1516060800000,1,(3) Tuesday,1,(01) January,2018,Yes,Yes,20 to 24,...,Unknown,Unknown,Unknown,33.4241,-111.9532,None,None,Evening,POINT (-111.95320 33.42410),2018-01
468,469,1517443200000,3,(5) Thursday,2,(02) February,2018,Yes,NULL,25 to 29,...,No,Yes,No,33.4230,-111.9436,Veteran,None,Overnight,POINT (-111.94360 33.42300),2018-02
479,480,1518739200000,4,(6) Friday,2,(02) February,2018,Yes,NULL,55 to 59,...,No,Unknown,Unknown,33.4309,-111.9475,None,None,Evening,POINT (-111.94750 33.43090),2018-02
523,524,1521504000000,1,(3) Tuesday,3,(03) March,2018,Yes,NULL,25 to 29,...,No,No,No,33.4288,-111.9567,None,None,Afternoon,POINT (-111.95670 33.42880),2018-03
571,572,1524700800000,3,(5) Thursday,4,(04) April,2018,Yes,Yes,35 to 39,...,No,No,No,33.4255,-111.9572,None,None,Morning,POINT (-111.95720 33.42550),2018-04

In [139]:
#All EMS Opioid Call data in Tempe aggregated by Month/Year
with open('DataFiles/emsPulledData_0118_0819.pkl', 'wb') as pkl_file:
    pkl.dump(ems_test, pkl_file)

In [140]:
#CREATING EMS DATAFRAME AGGREGATED BY MONTH FOR EACH TRACT
ems_df_full_mnyr = pd.DataFrame()
#ems_df_full.columns = odf.columns

odf = tempe_tract_df

for i in range(len(tempe)):
    df = ems_test[ems_test.within(odf.loc[i,'geometry'])]
    ems_monthly = df.filter(['Month_Year', 'Opioid_Use']).groupby('Month_Year').count()
    num = []
    for m in ems_monthly['Opioid_Use']:
        n = m
        num.append(m)
    months = list(np.unique(df['Month_Year']))
    x = len(ems_monthly['Opioid_Use'])
    t = pd.DataFrame(odf.loc[i]).T
    e_m = pd.DataFrame(np.repeat(t.values,x,axis=0))
    e_m.columns = t.columns
    e_m['Month'] = months
    e_m['Opioid_Use_EMS'] = num
    ems_df_full_mnyr = ems_df_full_mnyr.append(e_m)

ems_df_full_mnyr

,TempeTracts_NAME,PctPopUnder5,PctPop5_17,PctPop18_24,PctPop25_44,PctPop45_64,PctPop65_Up,PctEmpUnder16,PctEmp16_24,PctEmp25_44,...,PctUnemp45_64,PctCollegeGrad,PctNotHSGrad,PctNoHealthIns,PctOneHealthIns,PctTwoHealthIns,PctBelowPoverty,geometry,Month,Opioid_Use_EMS
0,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-01,1.0
1,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-02,2.0
2,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-03,1.0
3,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-04,1.0
4,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-08,1.0
5,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2018-09,1.0
6,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-01,1.0
7,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-02,1.0
8,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-03,1.0
9,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-04,1.0
10,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-06,1.0
11,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-07,1.0
12,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",2019-08,1.0
0,3191.01,2.96,7.2,62.63,21.26,5.95,0,87.71,91.14,83.3,...,16.95,16.26,36.48,23.23,70.4,6.37,73.11,"POLYGON ((-111.926293000195 33.4191529990701, ...",2018-02,1.0
1,3191.01,2.96,7.2,62.63,21.26,5.95,0,87.71,91.14,83.3,...,16.95,16.26,36.48,23.23,70.4,6.37,73.11,"POLYGON ((-111.926293000195 33.4191529990701, ...",2019-06,1.0
0,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-05,3.0
1,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-06,1.0
2,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-07,2.0
3,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-08,1.0
4,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-09,1.0
5,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2018-12,1.0
6,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-01,2.0
7,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-02,1.0
8,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-03,1.0
9,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-05,1.0
10,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-06,2.0
11,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",2019-07,1.0
0,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",2018-05,2.0
1,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",2018-06,2.0
2,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",2018-07,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",2019-06,3.0
15,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",2019-07,1.0
16,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",2019-08,2.0
0,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2018-04,1.0
1,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2018-05,1.0
2,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2018-06,1.0
3,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2018-12,1.0
4,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2019-01,1.0
5,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2019-06,1.0
6,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2019-07,2.0
7,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",2019-08,1.0
0,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2018-02,1.0
1,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2018-03,2.0
2,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2018-05,1.0
3,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2018-07,1.0
4,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2018-08,1.0
5,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2019-03,1.0
6,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2019-04,1.0
7,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2019-06,1.0
8,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",2019-08,1.0
0,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2018-01,1.0
1,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2018-03,1.0
2,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2018-04,1.0
3,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2018-09,1.0
4,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2018-11,1.0
5,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2019-02,1.0
6,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2019-07,1.0
7,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",2019-08,1.0
0,3199.07,3.36,21.33,5.71,13.94,41.02,14.65,97.5,86.67,97.98,...,0.86,5.31,67.79,2.6,85.68,11.71,1.38,"POLYGON ((-111.928473999766 33.34800799899, -1...",2018-10,1.0
0,3185.01,5.92,12.74,9.19,38.77,21.9,11.48,94.58,96.68,93.61,...,4.66,13.22,29.73,15.72,67.49,16.79,15.53,"POLYGON ((-111.943128000406 33.4551579994163, ...",2018-02,1.0

In [141]:
with open('DataFiles/emsCensusTract0118_0819.pkl', 'wb') as pkl_file:
    pkl.dump(ems_df_full_mnyr, pkl_file)

**This is to get EMS data aggregated strictly by month (so 2018 and 2019 together) by census tract

In [142]:
#CREATING EMS DATAFRAME AGGREGATED BY MONTH [NOT MONTH/YEAR] FOR EACH TRACT

ems_df_full = pd.DataFrame()
#ems_df_full.columns = odf.columns

odf = tempe_tract_df

for i in range(len(tempe)):
    df = ems_allc[ems_allc.within(odf.loc[i,'geometry'])]
    ems_monthly = df.filter(['Month_Sort', 'Opioid_Use']).groupby('Month_Sort').count()
    num = []
    for m in ems_monthly['Opioid_Use']:
        n = m
        num.append(m)
    months = list(np.unique(df['Month_Sort']))
    x = len(ems_monthly['Opioid_Use'])
    t = pd.DataFrame(odf.loc[i]).T
    e_m = pd.DataFrame(np.repeat(t.values,x,axis=0))
    e_m.columns = t.columns
    e_m['Month'] = months
    e_m['Opioid_Use_EMS'] = num
    ems_df_full = ems_df_full.append(e_m)

ems_df_full

,TempeTracts_NAME,PctPopUnder5,PctPop5_17,PctPop18_24,PctPop25_44,PctPop45_64,PctPop65_Up,PctEmpUnder16,PctEmp16_24,PctEmp25_44,...,PctUnemp45_64,PctCollegeGrad,PctNotHSGrad,PctNoHealthIns,PctOneHealthIns,PctTwoHealthIns,PctBelowPoverty,geometry,Month,Opioid_Use_EMS
0,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(01) January,2.0
1,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(02) February,3.0
2,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(03) March,2.0
3,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(04) April,2.0
4,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(06) June,1.0
5,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(07) July,1.0
6,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(08) August,2.0
7,3188,3.31,5.66,34.89,40.73,10.6,4.81,96.81,97.12,96.58,...,2.32,12.68,39.62,21.51,66.77,11.72,31.48,"POLYGON ((-111.961324999619 33.4371869993457, ...",(09) September,1.0
0,3191.01,2.96,7.2,62.63,21.26,5.95,0,87.71,91.14,83.3,...,16.95,16.26,36.48,23.23,70.4,6.37,73.11,"POLYGON ((-111.926293000195 33.4191529990701, ...",(02) February,1.0
1,3191.01,2.96,7.2,62.63,21.26,5.95,0,87.71,91.14,83.3,...,16.95,16.26,36.48,23.23,70.4,6.37,73.11,"POLYGON ((-111.926293000195 33.4191529990701, ...",(06) June,1.0
0,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(01) January,2.0
1,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(02) February,1.0
2,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(03) March,1.0
3,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(05) May,4.0
4,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(06) June,3.0
5,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(07) July,3.0
6,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(08) August,1.0
7,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(09) September,1.0
8,3189,3.38,6.06,31.45,31.21,19.71,8.2,93.78,95.67,92.52,...,7.35,8.23,49.23,14.98,72.25,12.77,27.87,"POLYGON ((-111.960895999762 33.4219539993975, ...",(12) December,1.0
0,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",(02) February,1.0
1,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",(05) May,3.0
2,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",(06) June,2.0
3,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",(07) July,4.0
4,3190,0.82,2.07,81.56,10.22,3.72,1.6,88.55,85.07,100,...,0,0,63.3,10.87,77.17,11.96,34.24,"POLYGON ((-111.943580000341 33.4150549990933, ...",(08) August,2.0
0,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(01) January,1.0
1,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(02) February,3.0
2,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(04) April,2.0
3,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(05) May,2.0
4,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(07) July,2.0
5,3194.03,5.9,16.18,10.82,29.77,23.43,13.9,93.86,94.95,97.73,...,13.32,4.53,38.78,15.67,67.41,16.8,21.39,"POLYGON ((-111.909122000199 33.3941089991188, ...",(09) September,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(06) June,6.0
6,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(07) July,2.0
7,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(08) August,3.0
8,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(09) September,1.0
9,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(10) October,1.0
10,3187,0.33,1.47,81.59,9.58,5.27,1.77,89.57,86.72,97.66,...,2.75,1.62,78.2,9.31,80.81,9.88,40.34,"POLYGON ((-111.944189000249 33.4356469994003, ...",(11) November,1.0
0,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(01) January,1.0
1,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(04) April,1.0
2,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(05) May,1.0
3,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(06) June,2.0
4,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(07) July,2.0
5,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(08) August,1.0
6,3193,3.47,12.05,25.94,26.44,17.4,14.69,89.52,89.13,92.11,...,14.5,26.75,17.8,20.5,64.04,15.46,30.38,"POLYGON ((-111.891519999592 33.4137309993002, ...",(12) December,1.0
0,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(02) February,1.0
1,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(03) March,3.0
2,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(04) April,1.0
3,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(05) May,1.0
4,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(06) June,1.0
5,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(07) July,1.0
6,3194.01,2.87,11.71,17.24,36.54,18.36,13.27,95.2,93.08,98.27,...,10.15,4.58,36.78,14.25,70.62,15.13,14.99,"POLYGON ((-111.92867699993 33.3788109992393, -...",(08) August,2.0
0,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(01) January,1.0
1,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(02) February,1.0
2,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(03) March,1.0
3,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(04) April,1.0
4,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(07) July,1.0
5,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(08) August,1.0
6,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(09) September,1.0
7,3194.02,3.51,12.89,9.6,29.76,27,17.24,93.08,78.15,94.28,...,2.55,4.07,35.47,10.85,75.12,13.91,5.52,"POLYGON ((-111.909237000375 33.3799899993995, ...",(11) November,1.0
0,3199.07,3.36,21.33,5.71,13.94,41.02,14.65,97.5,86.67,97.98,...,0.86,5.31,67.79,2.6,85.68,11.71,1.38,"POLYGON ((-111.928473999766 33.34800799899, -1...",(10) October,1.0
0,3185.01,5.92,12.74,9.19,38.77,21.9,11.48,94.58,96.68,93.61,...,4.66,13.22,29.73,15.72,67.49,16.79,15.53,"POLYGON ((-111.943128000406 33.4551579994163, ...",(02) February,1.0

In [143]:
with open('DataFiles/emsCensusTract_Month.pkl', 'wb') as pkl_file:
    pkl.dump(ems_df_full, pkl_file)

### EMS Data in Collection Sites

In [144]:
#According to: https://factfinder.census.gov/faces/nav/jsf/pages/searchresults.xhtml?refresh=t
tracts = np.unique(tempe_tract_df['TempeTracts_NAME'])
print(tracts)
tracts_TP02 = [3185.01,3201,3187,3148,3190,3191.04,3191.03,3191.01,3192.02,3193,3192.01]
tracts_TP04 = [3197.04]
tracts_TP05 = [3201]

['3184' '3185.01' '3187' '3188' '3189' '3190' '3191.01' '3191.03'
 '3191.04' '3192.01' '3192.02' '3193' '3194.01' '3194.02' '3194.03'
 '3194.04' '3195' '3196' '3197.03' '3197.04' '3197.05' '3197.06' '3198'
 '3199.02' '3199.03' '3199.04' '3199.05' '3199.06' '3199.07' '3199.08'
 '3199.09' '3199.10' '3200.01' '3200.07' '3201' '8100' '8101']

**Dataset that is aggregated by month year.

In [145]:
emsTP02_mnyr = pd.DataFrame()

for i in tracts_TP02:
    i = str(i)
    edf = ems_df_full_mnyr[ems_df_full_mnyr['TempeTracts_NAME'].astype(str) == i]
    emsTP02_mnyr = emsTP02_mnyr.append(edf)



emsTP04_mnyr = pd.DataFrame()

for i in tracts_TP04:
    i = str(i)
    edf = ems_df_full_mnyr[ems_df_full_mnyr['TempeTracts_NAME'].astype(str) == i]
    emsTP04_mnyr = emsTP04_mnyr.append(edf)

    
emsTP05_mnyr = pd.DataFrame()
for i in tracts_TP05:
    i = str(i)
    edf = ems_df_full_mnyr[ems_df_full_mnyr['TempeTracts_NAME'].astype(str) == i]
    emsTP05_mnyr = emsTP05_mnyr.append(edf)

In [146]:
emsWastewaterSites_mnyr = pd.DataFrame()

emsWastewaterSites_mnyr = emsWastewaterSites_mnyr.append(emsTP02_mnyr, ignore_index=True)
emsWastewaterSites_mnyr = emsWastewaterSites_mnyr.append(emsTP04_mnyr, ignore_index=True)
emsWastewaterSites_mnyr = emsWastewaterSites_mnyr.append(emsTP05_mnyr, ignore_index=True)

In [147]:
with open('DataFiles/emsCallsTP02Census_mnyr.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP02_mnyr, pkl_file)
with open('DataFiles/emsCallsTP04Census_mnyr.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP04_mnyr, pkl_file)
with open('DataFiles/emsCallsTP05Census_mnyr.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP05_mnyr, pkl_file)

with open('DataFiles/emsWastewaterSites_mnyr.pkl', 'wb') as pkl_file:
    pkl.dump(emsWastewaterSites_mnyr, pkl_file)

**Dataset that is aggregated by just month (2018 and 2019 averaged together)

In [148]:
emsTP02 = pd.DataFrame()

for i in tracts_TP02:
    i = str(i)
    edf = ems_df_full[ems_df_full['TempeTracts_NAME'].astype(str) == i]
    emsTP02 = emsTP02.append(edf)


emsTP04 = pd.DataFrame()

for i in tracts_TP04:
    i = str(i)
    edf = ems_df_full[ems_df_full['TempeTracts_NAME'].astype(str) == i]
    emsTP04 = emsTP04.append(edf)

    
emsTP05 = pd.DataFrame()
for i in tracts_TP05:
    i = str(i)
    edf = ems_df_full[ems_df_full['TempeTracts_NAME'].astype(str) == i]
    emsTP05 = emsTP05.append(edf)

In [149]:
emsWastewaterSites = pd.DataFrame()

emsWastewaterSites = emsWastewaterSites.append(emsTP02, ignore_index=True)
emsWastewaterSites = emsWastewaterSites.append(emsTP04, ignore_index=True)
emsWastewaterSites = emsWastewaterSites.append(emsTP05, ignore_index=True)

In [150]:
with open('DataFiles/emsCallsTP02Census.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP02, pkl_file)
with open('DataFiles/emsCallsTP04Census.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP04, pkl_file)
with open('DataFiles/emsCallsTP05Census.pkl', 'wb') as pkl_file:
    pkl.dump(emsTP05, pkl_file)

with open('DataFiles/emsWastewaterSites.pkl', 'wb') as pkl_file:
    pkl.dump(emsWastewaterSites, pkl_file)

### EMS Data NOT in Collection Sites

In [151]:
tracts_IN = [3185.01,3201,3187,3148,3190,3191.04,3191.03,3191.01,3192.02,3193,3192.01,3197.04,3201]

tracts_OUT = [x for x in tracts if x not in tracts_IN]

**Dataset aggregated by Month/Year

In [152]:
emsNonCollection_mnyr = pd.DataFrame()

for i in tracts_OUT:
    i = str(i)
    edf = ems_df_full_mnyr[ems_df_full_mnyr['TempeTracts_NAME'].astype(str) == i]
    emsNonCollection_mnyr = emsNonCollection_mnyr.append(edf)

In [153]:
with open('DataFiles/emsCallsNotCollectionSiteCensus_mnyr.pkl', 'wb') as pkl_file:
    pkl.dump(emsNonCollection_mnyr, pkl_file)

**Dataset aggregated by Month (2018 and 2019 aggregated together)

In [154]:
emsNonCollection = pd.DataFrame()

for i in tracts_OUT:
    i = str(i)
    edf = ems_df_full[ems_df_full['TempeTracts_NAME'].astype(str) == i]
    emsNonCollection = emsNonCollection.append(edf)

In [155]:
with open('DataFiles/emsCallsNotCollectionSiteCensus.pkl', 'wb') as pkl_file:
    pkl.dump(emsNonCollection, pkl_file)

## Health Facilities
Pulled using TempeFacilitiesMMW